name: kanban_board
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  appflowy_board: ^0.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  dio: ^5.4.3+1
  animations: ^2.0.11
  fluttertoast: ^8.2.6
  pretty_dio_logger: ^1.3.1
  flutter_cache_manager: ^3.3.2
  permission_handler: ^11.3.1
  go_router: ^14.1.4
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

